export const PAGE_SEARCH_CONFIG = {
  // Home Page
  home: [
    {
      label: "Home – Overview",
      path: "/",
      sectionId: "home-hero",
      keywords: [
        // Brand & Core
        "rosewood gardens",
        "rosewood gardens aged care",
        "bkv aged care",
        "best aged care provider",
        "trusted aged care",

        // Services
        "aged care services",
        "disability care services",
        "ndis registered provider",
        "support at home provider",
        "private residential aged care",
        "respite care melbourne",
        "palliative care melbourne",

        // Locations
        "aged care melbourne",
        "aged care sydney",
        "ndis provider melbourne",
        "ndis provider sydney",
        "support at home melbourne",
        "support at home sydney",

        // Intent Based
        "compassionate care",
        "24 7 nursing care",
        "clinical aged care",
        "high quality disability care",
        "person centred care",
        "holistic care",

        // General SEO
        "home",
        "homepage",
        "overview",
        "start here",
        "care near me",
        "aged care near me",
        "ndis support near me",
        "home care near me",
      ],
    },

    {
      label: "Home – Our Services",
      path: "/",
      sectionId: "services",
      keywords: [
        // Service Categories
        "our services",
        "what we do",
        "residential aged care",
        "aged care facility",
        "disability care facility",
        "ndis support services",
        "support at home services",
        "private self funded care",

        // Clinical
        "24 7 nursing care",
        "registered nurses onsite",
        "clinical care",
        "medication management",
        "wound care",
        "high intensity care",

        // Funding
        "ndis funded care",
        "home care package",
        "hcp services",
        "support at home funding",
        "private aged care options",

        // Keywords for ranking
        "patient centred care",
        "personalised care plans",
        "aged care programs",
        "disability support programs",
        "home care services",
        "in home care support",
      ],
    },

    {
      label: "Home – About Rosewood Gardens",
      path: "/",
      sectionId: "home-about",
      keywords: [
        // Brand Trust
        "about rosewood gardens",
        "about bkv aged care",
        "trusted aged care provider",
        "family owned aged care",
        "reliable aged care services",

        // Care Philosophy
        "person centred care philosophy",
        "dignity and respect in care",
        "family focused care",
        "transforming care into comfort",
        "compassion driven care",

        // Authority
        "registered care provider",
        "ndis approved provider",
        "aged care quality standards",
        "disability care compliance",

        // Story Keywords
        "who we are",
        "our story",
        "our background",
        "our care journey",
        "family feel care",
      ],
    },

    {
      label: "Home – Facilities Snapshot",
      path: "/",
      sectionId: "home-facilities",
      keywords: [
        // Facilities
        "aged care facilities melbourne",
        "disability care facilities melbourne",
        "residential care home melbourne",
        "supported independent living",
        "specialist disability accommodation",

        // Amenities
        "modern aged care facility",
        "private aged care rooms",
        "ensuite rooms aged care",
        "medical grade care rooms",

        // Visual SEO
        "aged care gallery",
        "facility photos",
        "disability care photos",
        "residential care images",
        "virtual care facility tour",
      ],
    },

    {
      label: "Home – Testimonials & Stories",
      path: "/",
      sectionId: "home-testimonials",
      keywords: [
        "aged care reviews",
        "ndis reviews",
        "home care testimonials",
        "family feedback aged care",
        "client success stories",

        "trusted by families",
        "real family experiences",
        "disability care reviews",
        "rosewood gardens reviews",
        "google reviews aged care",
      ],
    },
  ],

  // About Page
  about: [
    {
      label: "About – Vision",
      path: "/about",
      sectionId: "about-vision",
      keywords: [
        "vision",
        "our vision",
        "future vision",
        "company vision",
        "care vision",
      ],
    },
    {
      label: "About – Mission",
      path: "/about",
      sectionId: "about-vision",
      keywords: [
        "mission",
        "our mission",
        "purpose",
        "company mission",
        "service mission",
      ],
    },
    {
      label: "About – Values",
      path: "/about",
      sectionId: "about-values",
      keywords: [
        "values",
        "our values",
        "compassion",
        "respect",
        "dignity",
        "integrity",
        "inclusivity",
        "collaboration",
        "excellence",
      ],
    },
    {
      label: "About – Why Choose Us",
      path: "/about",
      sectionId: "about-why-choose-us",
      keywords: [
        "why choose us",
        "care model",
        "in the community",
        "ashburton",
        "facility",
        "unique model",
        "service model",
      ],
    },
    {
      label: "About – Testimonials",
      path: "/about",
      sectionId: "about-testimonials",
      keywords: [
        "testimonials",
        "reviews",
        "customer reviews",
        "feedback",
        "residents",
        "families",
        "stories",
      ],
    },
    {
      label: "About – Team",
      path: "/about",
      sectionId: "about-team",
      keywords: [
        "team",
        "our team",
        "expertise",
        "skills",
        "care team",
        "staff",
        "clinicians",
      ],
    },
  ],

  // Support at home Page
  supportAtHome: [
    {
      label: "Support at Home – Overview",
      path: "/support-at-home",
      sectionId: "support-home-hero",
      keywords: [
        "support at home",
        "home care",
        "stay at home",
        "care at home",
        "support program",
        "older australians",
        "live well at home",
      ],
    },
    {
      label: "Support at Home – Care in Your Own Home",
      path: "/support-at-home",
      sectionId: "support-home-care-at-home",
      keywords: [
        "care in your own home",
        "nursing at home",
        "personal care",
        "domestic assistance",
        "home help",
        "in-home support",
      ],
    },
    {
      label: "Support at Home – Care at Rosewood Gardens",
      path: "/support-at-home",
      sectionId: "support-home-care-at-rosewood",
      keywords: [
        "care at rosewood gardens",
        "short stay",
        "respite",
        "community connection",
        "therapy at facility",
        "residential day programs",
      ],
    },
    {
      label: "Support at Home – Service Categories",
      path: "/support-at-home",
      sectionId: "support-home-categories",
      keywords: [
        "clinical supports",
        "independence",
        "everyday living",
        "service categories",
        "nursing",
        "allied health",
        "transport",
        "meals",
        "gardening",
      ],
    },
    {
      label: "Support at Home – How It Works",
      path: "/support-at-home",
      sectionId: "support-home-how-it-works",
      keywords: [
        "how support at home works",
        "quarterly budgets",
        "10% care management",
        "care management",
        "statements",
        "rollover funds",
        "budget",
        "funding structure",
      ],
    },
    {
      label: "Support at Home – Assistive Technology & Home Modifications",
      path: "/support-at-home",
      sectionId: "support-home-at-hm",
      keywords: [
        "assistive technology",
        "AT-HM",
        "home modifications",
        "equipment",
        "rails",
        "ramps",
        "independent and safe",
        "at home equipment",
      ],
    },
    {
      label: "Support at Home – Short-Term Pathways",
      path: "/support-at-home",
      sectionId: "support-home-pathways",
      keywords: [
        "short term pathways",
        "transition support",
        "short stays",
        "reablement",
        "step-down care",
        "after hospital",
        "pathways",
      ],
    },
    {
      label: "Support at Home – Contributions",
      path: "/support-at-home",
      sectionId: "support-home-contributions",
      keywords: [
        "contributions",
        "fees",
        "costs",
        "no contributions",
        "5–25%",
        "17.5–85%",
        "government contributions",
        "participant contribution",
      ],
    },
    {
      label: "Support at Home – Price List",
      path: "/support-at-home",
      sectionId: "support-home-price-list",
      keywords: [
        "support at home price list",
        "pricing",
        "hourly rate",
        "service prices",
        "view price list",
        "detailed pricing",
      ],
    },
    {
      label: "Support at Home – FAQs",
      path: "/support-at-home",
      sectionId: "support-home-faq",
      keywords: [
        "support at home faq",
        "faq",
        "support at home questions",
        "care management 10%",
        "unspent funds",
        "rollover",
        "equipment included",
        "home modifications included",
        "do i need to pay",
        "when does support at home start",
      ],
    },
    {
      label: "Support at Home – Get Started",
      path: "/support-at-home",
      sectionId: "support-home-cta",
      keywords: [
        "book a care plan call",
        "get started",
        "ready to get started",
        "talk to care manager",
        "care plan",
        "support at home contact",
      ],
    },
  ],

  // Facilities Page
  facilities: [
    {
      label: "Facilities – Overview",
      path: "/facilities",
      sectionId: "facilities-overview",
      keywords: [
        "supported residential service",
        "ashburton",
        "aged care facility",
        "disability care facility",
        "supported residential aged care",
        "private aged care",
        "safe environment",
      ],
    },
    {
      label: "Facilities – Life at Rosewood Gardens",
      path: "/facilities",
      sectionId: "facilities-life",
      keywords: [
        "life at rosewood gardens",
        "residential care",
        "residential facility",
        "activities",
        "wellbeing",
        "community",
        "allied health",
        "gardens",
        "lounges",
      ],
    },
    {
      label: "Facilities – Residential Accommodation & Type of Care",
      path: "/facilities",
      sectionId: "facilities-accommodation",
      keywords: [
        "residential accommodation",
        "type of care",
        "24/7 nursing",
        "clinical support",
        "respite care",
        "palliative care",
        "post surgery",
        "ageing in place",
        "dementia support",
        "tac approved",
        "ndis provider",
        "support at home provider",
      ],
    },
    {
      label: "Facilities – Feels Like Home",
      path: "/facilities",
      sectionId: "facilities-home-feel",
      keywords: [
        "feels like home",
        "independence",
        "dignity",
        "family visits",
        "personalised care",
        "meaningful routines",
        "homelike environment",
      ],
    },
    {
      label: "Facilities – Rooms & Amenities",
      path: "/facilities",
      sectionId: "facilities-amenities",
      keywords: [
        "facilities",
        "single rooms",
        "ensuite",
        "dining room",
        "lounges",
        "activity rooms",
        "hairdressing",
        "library",
        "landscaped gardens",
        "gazebo",
        "courtyard",
      ],
    },
    {
      label: "Facilities – Care Options",
      path: "/facilities",
      sectionId: "facilities-care-options",
      keywords: [
        "care options",
        "24/7 nursing and clinical care",
        "respite",
        "palliative",
        "ageing in place",
        "ndis support",
        "sil",
        "support at home",
        "tac",
        "specialist dementia",
        "high intensity ndis care",
      ],
    },
    {
      label: "Facilities – What Makes Us Different",
      path: "/facilities",
      sectionId: "facilities-what-makes-different",
      keywords: [
        "what makes rosewood gardens different",
        "clinical excellence",
        "dedicated staff assignment",
        "nutritious dining",
        "lifestyle programs",
        "wellbeing programs",
        "safety and security",
      ],
    },
    {
      label: "Facilities – Book a Tour",
      path: "/facilities",
      sectionId: "facilities-book-tour",
      keywords: [
        "book a tour",
        "book a visit",
        "facility tour",
        "inspection",
        "visit rosewood gardens",
      ],
    },
    {
      label: "Facilities – Photo Gallery",
      path: "/facilities",
      sectionId: "facilities-gallery",
      keywords: [
        "photos",
        "gallery",
        "pictures",
        "images",
        "see facility",
        "virtual tour",
      ],
    },
  ],

  // FAQ Page
  faq: [
    {
      label: "FAQ – General Questions",
      path: "/faq",
      sectionId: "faq-general",
      keywords: [
        "faq",
        "questions",
        "general questions",
        "rosewood gardens faq",
        "about rosewood gardens",
        "aged care questions",
        "disability care questions",
        "support options",
        "how can you support me",
        "family support",
      ],
    },
    {
      label: "FAQ – In-Home Care & HCP (Support at Home)",
      path: "/faq",
      sectionId: "faq-in-home-care",
      keywords: [
        "home care",
        "in-home care",
        "support at home",
        "hcp",
        "home care package",
        "use my hcp",
        "what does hcp cover",
        "support at home questions",
        "in-home aged care",
        "care at home",
      ],
    },
    {
      label: "FAQ – NDIS & SIL",
      path: "/faq",
      sectionId: "faq-ndis-sil",
      keywords: [
        "ndis",
        "ndis supports",
        "ndis package",
        "ndis plan",
        "support coordinator",
        "sil",
        "supported independent living",
        "sda",
        "specialist disability accommodation",
        "ndis services",
      ],
    },
    {
      label: "FAQ – Residential Care",
      path: "/faq",
      sectionId: "faq-residential-care",
      keywords: [
        "residential care",
        "aged care facility",
        "rooms",
        "single rooms",
        "ensuite",
        "24/7 nursing",
        "clinical care",
        "move into care",
        "live in the residence",
        "long-term stay",
      ],
    },
    {
      label: "FAQ – Costs & Funding",
      path: "/faq",
      sectionId: "faq-costs-funding",
      keywords: [
        "fees",
        "costs",
        "funding",
        "hcp funding",
        "ndis funding",
        "weekly fee",
        "rad",
        "dap",
        "bonds",
        "accommodation costs",
        "private self-funded care",
        "what is included",
        "what does it cover",
      ],
    },
    {
      label: "FAQ – Admissions & Tours",
      path: "/faq",
      sectionId: "faq-admissions-tours",
      keywords: [
        "admission",
        "admissions",
        "start receiving care",
        "how quickly can I start",
        "join rosewood gardens",
        "book a tour",
        "facility tour",
        "inspection",
        "visit the residence",
        "acat assessment",
        "eligibility",
      ],
    },
  ],

  // Contact Page
  contact: [
    {
      label: "Contact – Phone",
      path: "/contact-us",
      sectionId: "contact-data",
      keywords: [
        "phone",
        "call",
        "telephone",
        "mobile",
        "contact number",
        "phone number",
        "call us",
        "speak to us",
        "helpline",
        "customer support",
        "support phone",
        "care phone",
        "aged care phone",
        "home care phone",
        "ndis phone",
        "ndis contact number",
        "hcp contact",
        "hotline",
        "service number",
      ],
    },

    {
      label: "Contact – Email",
      path: "/contact-us",
      sectionId: "contact-data",
      keywords: [
        "email",
        "mail",
        "write to us",
        "contact email",
        "support email",
        "customer service email",
        "send email",
        "send message",
        "email address",
        "care email",
        "aged care email",
        "home care email",
        "ndis email",
        "hcp email",
        "service email",
      ],
    },

    {
      label: "Contact – Form",
      path: "/contact-us",
      sectionId: "form",
      keywords: [
        "form",
        "enquiry",
        "message",
        "contact form",
        "enquiry form",
        "send enquiry",
        "submit enquiry",
        "book a call",
        "request a callback",
        "request information",
        "ask a question",
        "apply for support",
        "care enquiry",
        "ndis enquiry",
        "hcp enquiry",
        "home care enquiry",
        "aged care enquiry",
      ],
    },
  ],

  // Contact Component
  contactComponent: [
    {
      label: "Contact – Form",
      path: "/",
      sectionId: "form",
      keywords: [
        "form",
        "enquiry",
        "message",
        "contact form",
        "enquiry form",
        "send enquiry",
        "submit enquiry",
        "book a call",
        "request a callback",
        "request information",
        "ask a question",
        "apply for support",
        "care enquiry",
        "ndis enquiry",
        "hcp enquiry",
        "home care enquiry",
        "aged care enquiry",
      ],
    },
  ],

  // Newsletter Component
  newsletter: [
    {
      label: "Newsletter – Subscribe",
      path: "/",
      sectionId: "newsletter-section",
      keywords: [
        "newsletter",
        "subscribe",
        "email newsletter",
        "newsletter signup",
        "subscribe to newsletter",
        "newsletter subscription",
        "email updates",
        "email subscription",
        "updates",
        "alerts",
        "notifications",
        "email alerts",
        "stay updated",
        "keep in touch",
        "subscribe for updates",
        "care updates",
        "service updates",
        "community events",
        "enhancing lives",
        "subscribe now",
        "mailing list",
        "newsletter form",
        "subscription form",
        "get updates",
        "receive updates",
        "latest news",
        "what's new",
        "new services",
        "event notifications",
        "care services newsletter",
        "rosewood gardens newsletter",
        "aged care newsletter",
        "disability care newsletter",
        "ndis updates",
        "hcp updates",
        "home care updates",
        "residential care news",
        "care tips",
        "wellbeing tips",
        "family resources",
        "caregiver resources",
      ],
    },
  ],

  // careerBanner Component
  careerBanner: [
    {
      label: "Career – Quality Promise",
      path: "/",
      sectionId: "career-banner-section",
      keywords: [
        // Core Concepts
        "quality promise",
        "quality commitment",
        "continuous improvement",
        "quality assurance",
        "quality standards",
        "care quality",
        "service quality",
        "quality care",

        // Safety & Security
        "safety",
        "safety & screening",
        "background checks",
        "staff screening",
        "vetting process",
        "safety protocols",
        "security screening",

        // Training & Development
        "training",
        "ongoing training",
        "staff training",
        "competency checks",
        "professional development",
        "skills development",
        "best practice training",
        "supervision",

        // Standards & Compliance
        "national aged care quality standards",
        "ndis practice standards",
        "compliance",
        "regulatory standards",
        "quality standards",
        "accreditation",
        "certification",

        // Improvement Processes
        "continuous improvement",
        "feedback reviews",
        "incident reviews",
        "internal audits",
        "service reviews",
        "quality improvement",
        "audit processes",

        // Brand Trust
        "commitment to quality",
        "rosewood gardens quality",
        "trusted care provider",
        "reliable services",
        "professional standards",

        // Alternative Terms
        "our promise",
        "our commitment",
        "quality framework",
        "care standards",
        "safety measures",
        "training programs",
        "quality system",
        "assurance processes",

        // Intent-Based
        "how we ensure quality",
        "our quality approach",
        "quality management",
        "safety procedures",
        "staff qualifications",
        "meeting standards",
        "exceeding standards",
      ],
    },
  ],

  // Terms Of use Page
  termsOfUse: [
    {
      label: "Terms of Use – Overview",
      path: "/term-of-conditions",
      sectionId: "terms-overview",
      keywords: [
        "terms of use",
        "terms and conditions",
        "terms",
        "legal terms",
        "website terms",
        "user agreement",
        "terms of service",
        "conditions of use",
        "terms & conditions",
        "agreement",
        "legal agreement",
        "site terms",
        "online terms",
        "web terms",
        "terms page",
        "terms of use page",
        "legal terms page",
        "user terms",
        "terms of access",
        "access terms",
        "usage terms",
        "terms policy",
        "terms document",
        "legal document",
        "terms overview",
        "terms introduction",
      ],
    },
    {
      label: "Terms of Use – Who we are",
      path: "/term-of-conditions",
      sectionId: "who-we-are",
      keywords: [
        "who we are",
        "about us",
        "company",
        "operator",
        "website operator",
        "site owner",
        "rosewood gardens terms",
        "bkv aged care",
        "company details",
        "business information",
        "legal entity",
        "abn",
        "trading as",
        "operated by",
        "privacy policy link",
        "terms and privacy",
        "legal information",
        "company background",
        "entity information",
      ],
    },
    {
      label: "Terms of Use – Website content",
      path: "/term-of-conditions",
      sectionId: "website-content",
      keywords: [
        "website content",
        "content",
        "information",
        "general information",
        "not advice",
        "not professional advice",
        "general nature",
        "not medical advice",
        "not clinical advice",
        "not legal advice",
        "not financial advice",
        "emergency",
        "emergency contact",
        "000",
        "disclaimer",
        "content disclaimer",
        "information disclaimer",
        "advice disclaimer",
        "professional advice",
        "qualified professionals",
        "emergency services",
        "content purpose",
        "information purpose",
      ],
    },
    {
      label: "Terms of Use – Your responsibilities",
      path: "/term-of-conditions",
      sectionId: "your-responsibilities",
      keywords: [
        "your responsibilities",
        "responsibilities",
        "user responsibilities",
        "site use",
        "lawful use",
        "intended purpose",
        "proper use",
        "no disruption",
        "no hacking",
        "no compromise",
        "security",
        "form accuracy",
        "accurate details",
        "respect privacy",
        "user obligations",
        "user duties",
        "acceptable use",
        "prohibited activities",
        "site rules",
        "user rules",
        "conduct",
        "user conduct",
        "behavior",
        "ethical use",
        "legal use",
      ],
    },
    {
      label: "Terms of Use – Intellectual property",
      path: "/term-of-conditions",
      sectionId: "intellectual-property",
      keywords: [
        "intellectual property",
        "copyright",
        "ownership",
        "content ownership",
        "licensed content",
        "personal use",
        "view content",
        "print content",
        "reproduction",
        "distribution",
        "adaptation",
        "prior consent",
        "written consent",
        "permission",
        "copyright notice",
        "ip rights",
        "trademarks",
        "brand ownership",
        "content license",
        "usage rights",
        "rights reserved",
        "copyright policy",
        "ip policy",
        "content use",
        "restrictions",
      ],
    },
    {
      label: "Terms of Use – Third-party sites",
      path: "/term-of-conditions",
      sectionId: "third-party-sites",
      keywords: [
        "third-party sites",
        "third-party links",
        "external links",
        "other websites",
        "linked sites",
        "external sites",
        "no control",
        "not responsible",
        "third-party content",
        "third-party practices",
        "link disclaimer",
        "external content",
        "off-site links",
        "reference links",
        "convenience links",
        "third-party disclaimer",
        "link policy",
        "external website policy",
        "site links",
        "hyperlink policy",
      ],
    },
    {
      label: "Terms of Use – Liability",
      path: "/term-of-conditions",
      sectionId: "liability",
      keywords: [
        "liability",
        "disclaimer",
        "warranties",
        "exclusion",
        "liability exclusion",
        "warranty exclusion",
        "loss",
        "damage",
        "cost",
        "site use liability",
        "australian consumer law",
        "consumer guarantees",
        "consumer rights",
        "consumer law",
        "legal liability",
        "limited liability",
        "no liability",
        "liability limitation",
        "risk",
        "user risk",
        "assumption of risk",
        "legal disclaimer",
        "liability clause",
        "indemnification",
        "hold harmless",
      ],
    },
    {
      label: "Terms of Use – Indemnity",
      path: "/term-of-conditions",
      sectionId: "indemnity",
      keywords: [
        "indemnity",
        "indemnify",
        "hold harmless",
        "breach",
        "misuse",
        "officers",
        "employees",
        "contractors",
        "claims",
        "loss",
        "liability",
        "indemnification",
        "protection",
        "legal protection",
        "company protection",
        "breach of terms",
        "misuse of site",
        "user indemnity",
        "indemnity clause",
        "legal indemnity",
        "compensation",
        "damages",
        "defend",
        "defense",
        "legal defense",
      ],
    },
    {
      label: "Terms of Use – Changes to terms",
      path: "/term-of-conditions",
      sectionId: "changes-to-terms",
      keywords: [
        "changes to terms",
        "updates",
        "term updates",
        "site updates",
        "modification",
        "changes",
        "revision",
        "updated terms",
        "effective date",
        "publication date",
        "change policy",
        "modification right",
        "right to modify",
        "right to update",
        "term changes",
        "notification",
        "no notification",
        "automatic updates",
        "term revisions",
        "policy changes",
        "terms modification",
      ],
    },
    {
      label: "Terms of Use – Governing law",
      path: "/term-of-conditions",
      sectionId: "governing-law",
      keywords: [
        "governing law",
        "jurisdiction",
        "victoria",
        "australia",
        "australian law",
        "victorian law",
        "courts",
        "legal jurisdiction",
        "non-exclusive jurisdiction",
        "applicable law",
        "legal venue",
        "court venue",
        "law governing",
        "legal system",
        "dispute resolution",
        "legal forum",
        "choice of law",
        "forum selection",
        "legal proceedings",
        "court proceedings",
      ],
    },
    {
      label: "Terms of Use – Contact",
      path: "/term-of-conditions",
      sectionId: "contact-terms",
      keywords: [
        "contact terms",
        "questions",
        "terms questions",
        "inquiries",
        "email",
        "info email",
        "contact email",
        "terms contact",
        "queries",
        "clarifications",
        "support",
        "terms support",
        "legal questions",
        "contact information",
        "terms inquiries",
        "get help",
        "ask questions",
        "contact details",
        "email contact",
        "mail contact",
        "contact us terms",
      ],
    },
  ],

  // Clinical Disclaimer Page
  clinicalDisclaimer: [
    {
      label: "Clinical Disclaimer – Overview",
      path: "/clinical-disclaimer",
      sectionId: "clinical-disclaimer-overview",
      keywords: [
        "clinical disclaimer",
        "medical disclaimer",
        "health disclaimer",
        "disclaimer",
        "clinical information",
        "medical information",
        "health information",
        "website disclaimer",
        "site disclaimer",
        "content disclaimer",
        "information disclaimer",
        "professional advice disclaimer",
        "general information",
        "not a substitute",
        "not professional advice",
        "disclaimer page",
        "legal disclaimer",
        "medical disclaimer page",
        "clinical disclaimer page",
        "health disclaimer page",
        "notice",
        "important notice",
        "warning",
        "caution",
        "important information",
        "read this first",
        "disclaimer statement",
        "disclaimer notice",
      ],
    },
    {
      label: "Clinical Disclaimer – General information",
      path: "/clinical-disclaimer",
      sectionId: "general-information",
      keywords: [
        "general information",
        "general information only",
        "for information only",
        "informational purposes",
        "educational purposes",
        "not medical advice",
        "not clinical advice",
        "not professional advice",
        "not a substitute",
        "seek professional advice",
        "qualified health professional",
        "medical professional",
        "health professional",
        "doctor",
        "physician",
        "clinician",
        "medical condition",
        "health questions",
        "medical questions",
        "always seek advice",
        "professional consultation",
        "consult a professional",
        "get professional help",
        "medical consultation",
        "clinical consultation",
        "health consultation",
      ],
    },
    {
      label: "Clinical Disclaimer – Emergencies",
      path: "/clinical-disclaimer",
      sectionId: "emergencies",
      keywords: [
        "emergencies",
        "emergency",
        "medical emergency",
        "health emergency",
        "emergency contact",
        "000",
        "triple zero",
        "emergency services",
        "call 000",
        "immediately",
        "urgent care",
        "urgent medical",
        "emergency help",
        "emergency assistance",
        "emergency response",
        "life-threatening",
        "serious condition",
        "acute condition",
        "emergency warning",
        "emergency advice",
        "emergency protocol",
        "emergency procedure",
        "when to call 000",
        "emergency situations",
        "medical crisis",
        "health crisis",
      ],
    },
    {
      label: "Clinical Disclaimer – No client relationship",
      path: "/clinical-disclaimer",
      sectionId: "no-client-relationship",
      keywords: [
        "no client relationship",
        "no client-provider relationship",
        "no doctor-patient relationship",
        "no therapeutic relationship",
        "no professional relationship",
        "does not create relationship",
        "not a client",
        "not a patient",
        "not established",
        "no relationship established",
        "website use only",
        "informational only",
        "no treatment relationship",
        "no care relationship",
        "no clinical relationship",
        "no medical relationship",
        "no formal relationship",
        "relationship disclaimer",
        "professional relationship disclaimer",
        "client relationship disclaimer",
        "provider relationship disclaimer",
        "medical relationship disclaimer",
        "clinical relationship disclaimer",
      ],
    },
    {
      label: "Clinical Disclaimer – Third-party content",
      path: "/clinical-disclaimer",
      sectionId: "third-party-content",
      keywords: [
        "third-party content",
        "external sites",
        "external links",
        "linked sites",
        "other websites",
        "external content",
        "third-party sites",
        "third-party links",
        "not responsible",
        "no responsibility",
        "no control",
        "external website content",
        "linked content",
        "reference sites",
        "resource links",
        "third-party information",
        "external information",
        "linked resources",
        "third-party resources",
        "external resources",
        "website links",
        "hyperlink content",
        "external reference",
        "third-party reference",
        "link disclaimer",
        "external link disclaimer",
      ],
    },
    {
      label: "Clinical Disclaimer – Liability",
      path: "/clinical-disclaimer",
      sectionId: "liability-disclaimer",
      keywords: [
        "liability",
        "disclaimer liability",
        "no liability",
        "limited liability",
        "not liable",
        "no responsibility",
        "loss",
        "damage",
        "harm",
        "reliance",
        "reliance on information",
        "information reliance",
        "site information",
        "website information",
        "content reliance",
        "risk",
        "assumption of risk",
        "user risk",
        "your risk",
        "legal liability",
        "liability exclusion",
        "liability limitation",
        "liability disclaimer",
        "hold harmless",
        "indemnity",
        "waiver",
        "responsibility waiver",
        "liability waiver",
        "risk waiver",
      ],
    },
  ],

  // Privacy Policy Page
  privacyPolicy: [
    {
      label: "Privacy Policy – Overview",
      path: "/privacypolicy",
      sectionId: "privacy-policy-overview",
      keywords: [
        "privacy policy",
        "privacy",
        "data protection",
        "privacy statement",
        "privacy notice",
        "data privacy",
        "personal information",
        "data policy",
        "privacy practices",
        "information privacy",
        "privacy commitment",
        "privacy terms",
        "privacy agreement",
        "privacy document",
        "privacy information",
        "website privacy",
        "site privacy",
        "online privacy",
        "digital privacy",
        "privacy rights",
        "privacy overview",
        "privacy introduction",
        "privacy summary",
        "data handling",
        "information handling",
      ],
    },
    {
      label: "Privacy Policy – At a glance",
      path: "/privacypolicy",
      sectionId: "at-a-glance",
      keywords: [
        "at a glance",
        "summary",
        "quick summary",
        "overview summary",
        "key points",
        "main points",
        "highlight",
        "highlights",
        "important points",
        "essential information",
        "key takeaways",
        "summary points",
        "brief overview",
        "executive summary",
        "tl;dr",
        "too long didn't read",
        "short summary",
        "quick overview",
        "policy summary",
        "privacy summary",
        "data summary",
        "information summary",
      ],
    },
    {
      label: "Privacy Policy – Who we are and scope",
      path: "/privacypolicy",
      sectionId: "who-we-are-scope",
      keywords: [
        "who we are",
        "scope",
        "policy scope",
        "coverage",
        "what this covers",
        "who this applies to",
        "applicability",
        "application",
        "coverage scope",
        "policy coverage",
        "privacy scope",
        "data scope",
        "information scope",
        "legal entity",
        "company information",
        "business details",
        "organization",
        "organization details",
        "company scope",
        "business scope",
        "service scope",
        "coverage area",
        "policy application",
        "who is covered",
      ],
    },
    {
      label: "Privacy Policy – What we collect",
      path: "/privacypolicy",
      sectionId: "what-we-collect",
      keywords: [
        "what we collect",
        "data collection",
        "information collection",
        "what data",
        "what information",
        "collected data",
        "collected information",
        "personal data",
        "personal details",
        "contact information",
        "identity information",
        "health information",
        "medical information",
        "clinical information",
        "care information",
        "support information",
        "funding information",
        "billing information",
        "employment information",
        "online data",
        "device data",
        "cookies data",
        "analytics data",
        "media data",
        "photos videos",
        "testimonials",
        "feedback",
        "sensitive information",
        "confidential information",
        "private information",
      ],
    },
    {
      label: "Privacy Policy – How we collect",
      path: "/privacypolicy",
      sectionId: "how-we-collect",
      keywords: [
        "how we collect",
        "collection methods",
        "data collection methods",
        "information collection methods",
        "collection process",
        "how data is collected",
        "how information is collected",
        "direct collection",
        "from you",
        "directly from you",
        "forms",
        "phone",
        "email",
        "meetings",
        "assessments",
        "service delivery",
        "authorized representative",
        "family",
        "guardian",
        "plan manager",
        "referrers",
        "care partners",
        "my aged care",
        "clinicians",
        "allied health",
        "support coordinators",
        "automatically",
        "website",
        "cookies",
        "analytics",
        "recruitment",
        "applications",
        "screening",
        "onboarding",
        "data sources",
        "information sources",
      ],
    },
    {
      label: "Privacy Policy – Why we use your information",
      path: "/privacypolicy",
      sectionId: "why-we-use",
      keywords: [
        "why we use",
        "purpose",
        "use of information",
        "use of data",
        "why we need",
        "purpose of collection",
        "use purpose",
        "data use",
        "information use",
        "service delivery",
        "care delivery",
        "support coordination",
        "communication",
        "billing",
        "funding",
        "compliance",
        "legal obligations",
        "regulatory requirements",
        "reporting",
        "safety",
        "quality",
        "audits",
        "incidents",
        "continuous improvement",
        "recruitment",
        "staff management",
        "training",
        "website improvement",
        "service improvement",
        "updates",
        "marketing",
        "not selling",
        "no sale",
        "don't sell",
      ],
    },
    {
      label: "Privacy Policy – When we disclose information",
      path: "/privacypolicy",
      sectionId: "when-we-disclose",
      keywords: [
        "when we disclose",
        "disclosure",
        "information sharing",
        "data sharing",
        "who we share with",
        "third parties",
        "authorized representatives",
        "family",
        "clinicians",
        "hospitals",
        "allied health",
        "care providers",
        "funding bodies",
        "services australia",
        "my aged care",
        "ndis",
        "plan managers",
        "regulators",
        "aged care quality",
        "ndis quality",
        "service partners",
        "it providers",
        "insurers",
        "professional advisers",
        "legal",
        "accounting",
        "audit",
        "law enforcement",
        "authorities",
        "police",
        "emergency",
        "safety",
        "health threat",
        "legal claims",
        "court",
        "legal proceedings",
      ],
    },
    {
      label: "Privacy Policy – Overseas disclosure",
      path: "/privacypolicy",
      sectionId: "overseas-disclosure",
      keywords: [
        "overseas disclosure",
        "international disclosure",
        "cross-border",
        "data transfer",
        "international data",
        "overseas data",
        "cloud storage",
        "data storage",
        "international storage",
        "data hosting",
        "cloud hosting",
        "email hosting",
        "data protection",
        "international protection",
        "safeguards",
        "security measures",
        "contractual obligations",
        "app compliance",
        "privacy act compliance",
        "australian privacy",
        "data location",
        "where data is stored",
        "data jurisdiction",
        "international privacy",
        "global data",
      ],
    },
    {
      label: "Privacy Policy – Direct marketing",
      path: "/privacypolicy",
      sectionId: "direct-marketing",
      keywords: [
        "direct marketing",
        "marketing",
        "email marketing",
        "communications",
        "updates",
        "service updates",
        "promotions",
        "offers",
        "newsletters",
        "opt out",
        "unsubscribe",
        "preferences",
        "communication preferences",
        "marketing preferences",
        "email preferences",
        "subscription",
        "subscription management",
        "spam",
        "spam act",
        "commercial messages",
        "promotional messages",
        "service information",
        "how to unsubscribe",
        "how to opt out",
        "stop emails",
        "email settings",
        "communication settings",
        "marketing opt-out",
        "opt-out",
        "opt out of marketing",
      ],
    },
    {
      label: "Privacy Policy – Cookies and analytics",
      path: "/privacypolicy",
      sectionId: "cookies-analytics",
      keywords: [
        "cookies",
        "analytics",
        "website cookies",
        "tracking",
        "website tracking",
        "online tracking",
        "browser cookies",
        "web analytics",
        "google analytics",
        "website analytics",
        "performance",
        "website performance",
        "usage data",
        "website usage",
        "browser data",
        "device data",
        "ip address",
        "browser type",
        "pages viewed",
        "user behavior",
        "website statistics",
        "notifications",
        "browser notifications",
        "push notifications",
        "website notifications",
        "cookie settings",
        "cookie control",
        "cookie preferences",
        "privacy settings",
        "tracking settings",
        "opt-out cookies",
        "decline cookies",
        "cookie policy",
      ],
    },
    {
      label: "Privacy Policy – CCTV and site visitors",
      path: "/privacypolicy",
      sectionId: "cctv-site-visitors",
      keywords: [
        "cctv",
        "security cameras",
        "surveillance",
        "video surveillance",
        "camera surveillance",
        "site security",
        "premises security",
        "security footage",
        "video footage",
        "camera footage",
        "site visitors",
        "visitors",
        "guest security",
        "resident security",
        "staff security",
        "safety",
        "safety measures",
        "security measures",
        "monitoring",
        "video monitoring",
        "surveillance monitoring",
        "privacy and security",
        "security and privacy",
        "cctv policy",
        "video policy",
        "surveillance policy",
        "security policy",
        "footage retention",
        "video retention",
        "law enforcement access",
        "police access",
        "regulator access",
        "cctv signs",
        "surveillance notice",
      ],
    },
    {
      label: "Privacy Policy – Security",
      path: "/privacypolicy",
      sectionId: "security",
      keywords: [
        "security",
        "data security",
        "information security",
        "protection",
        "data protection",
        "information protection",
        "security measures",
        "protection measures",
        "technical measures",
        "physical measures",
        "organizational measures",
        "role-based access",
        "multi-factor authentication",
        "mfa",
        "two-factor authentication",
        "2fa",
        "encryption",
        "data encryption",
        "secure transmission",
        "secure premises",
        "staff training",
        "security training",
        "auditing",
        "security audits",
        "secure forms",
        "email security",
        "sensitive information",
        "confidential information",
        "data breach",
        "security breach",
        "notifiable data breach",
        "ndb scheme",
        "serious harm",
        "oaic notification",
        "breach notification",
        "security incident",
        "incident response",
      ],
    },
    {
      label: "Privacy Policy – Retention and deletion",
      path: "/privacypolicy",
      sectionId: "retention-deletion",
      keywords: [
        "retention",
        "deletion",
        "data retention",
        "information retention",
        "data deletion",
        "information deletion",
        "how long we keep",
        "storage period",
        "retention period",
        "retention policy",
        "deletion policy",
        "data disposal",
        "information disposal",
        "secure destruction",
        "secure deletion",
        "data destruction",
        "information destruction",
        "de-identification",
        "anonymization",
        "data anonymization",
        "information anonymization",
        "retention schedule",
        "legal requirements",
        "regulatory requirements",
        "business requirements",
        "care requirements",
        "medical records retention",
        "health records retention",
        "employee records retention",
        "financial records retention",
        "document retention",
        "record retention",
      ],
    },
    {
      label: "Privacy Policy – Access and correction",
      path: "/privacypolicy",
      sectionId: "access-correction",
      keywords: [
        "access",
        "correction",
        "access to information",
        "access to data",
        "right to access",
        "access rights",
        "correction rights",
        "right to correction",
        "data correction",
        "information correction",
        "update information",
        "correct information",
        "amend information",
        "rectify information",
        "request access",
        "request correction",
        "how to access",
        "how to correct",
        "privacy request",
        "data request",
        "information request",
        "subject access request",
        "privacy rights",
        "data rights",
        "information rights",
        "verification",
        "identity verification",
        "proof of identity",
        "identity check",
        "access limits",
        "correction limits",
        "legal limits",
        "privacy act rights",
        "apps rights",
      ],
    },
    {
      label: "Privacy Policy – Employment records",
      path: "/privacypolicy",
      sectionId: "employment-records",
      keywords: [
        "employment records",
        "employee records",
        "staff records",
        "employee information",
        "staff information",
        "employment information",
        "employee data",
        "staff data",
        "applicants",
        "job applicants",
        "applicant information",
        "recruitment information",
        "contractors",
        "contractor information",
        "volunteers",
        "volunteer information",
        "apps exemption",
        "privacy act exemption",
        "employee exemption",
        "workplace laws",
        "safety laws",
        "work health safety",
        "whs",
        "employment law",
        "workplace privacy",
        "employee privacy",
        "staff privacy",
        "applicant privacy",
        "contractor privacy",
        "volunteer privacy",
        "recruitment privacy",
        "hiring privacy",
        "onboarding privacy",
      ],
    },
    {
      label: "Privacy Policy – Children and decision-making",
      path: "/privacypolicy",
      sectionId: "children-decision-making",
      keywords: [
        "children",
        "minors",
        "under 18",
        "young people",
        "youth",
        "child privacy",
        "minor privacy",
        "parental consent",
        "parent consent",
        "guardian consent",
        "authorized representative",
        "legal guardian",
        "supported decision-making",
        "decision-making support",
        "capacity",
        "decision capacity",
        "informed consent",
        "consent",
        "permission",
        "authorization",
        "choice",
        "autonomy",
        "independence",
        "self-determination",
        "personal choice",
        "individual choice",
        "right to choose",
        "right to decide",
        "decision rights",
        "choice rights",
        "privacy rights for children",
        "minor's privacy",
        "child's privacy",
      ],
    },
    {
      label: "Privacy Policy – Complaints",
      path: "/privacypolicy",
      sectionId: "complaints",
      keywords: [
        "complaints",
        "privacy complaints",
        "data complaints",
        "information complaints",
        "concerns",
        "privacy concerns",
        "data concerns",
        "information concerns",
        "how to complain",
        "make a complaint",
        "file a complaint",
        "submit a complaint",
        "privacy issue",
        "data issue",
        "information issue",
        "report a problem",
        "report an issue",
        "feedback",
        "privacy feedback",
        "complaint process",
        "complaint procedure",
        "complaint handling",
        "complaint resolution",
        "response time",
        "acknowledgement",
        "resolution time",
        "oaic",
        "office of australian information commissioner",
        "information commissioner",
        "regulator",
        "external complaint",
        "escalation",
        "appeal",
        "dispute",
        "privacy dispute",
      ],
    },
    {
      label: "Privacy Policy – Changes to policy",
      path: "/privacypolicy",
      sectionId: "changes-policy",
      keywords: [
        "changes",
        "updates",
        "policy changes",
        "privacy changes",
        "policy updates",
        "privacy updates",
        "version",
        "policy version",
        "latest version",
        "current version",
        "effective date",
        "last updated",
        "update date",
        "modification",
        "policy modification",
        "revision",
        "policy revision",
        "amendments",
        "policy amendments",
        "changes notice",
        "update notice",
        "notification",
        "policy notification",
        "significant changes",
        "major changes",
        "minor changes",
        "change log",
        "version history",
        "policy history",
        "review",
        "policy review",
        "periodic review",
        "regular review",
      ],
    },
    {
      label: "Privacy Policy – Contact us",
      path: "/privacypolicy",
      sectionId: "contact-us",
      keywords: [
        "contact us",
        "contact",
        "get in touch",
        "reach us",
        "contact details",
        "contact information",
        "email",
        "email address",
        "mail",
        "postal",
        "phone",
        "telephone",
        "phone number",
        "contact number",
        "address",
        "physical address",
        "location",
        "office location",
        "business hours",
        "hours of operation",
        "opening hours",
        "support",
        "help",
        "assistance",
        "questions",
        "inquiries",
        "queries",
        "clarifications",
        "information request",
        "privacy contact",
        "data contact",
        "information contact",
        "privacy officer",
        "data protection officer",
        "privacy team",
        "compliance team",
      ],
    },
    {
      label: "Privacy Policy – Definitions",
      path: "/privacypolicy",
      sectionId: "definitions",
      keywords: [
        "definitions",
        "glossary",
        "terms",
        "terminology",
        "key terms",
        "important terms",
        "meaning",
        "interpretation",
        "explanation",
        "clarification",
        "personal information",
        "sensitive information",
        "health information",
        "medical information",
        "apps",
        "australian privacy principles",
        "privacy act",
        "privacy act 1988",
        "ndb scheme",
        "notifiable data breaches",
        "data breach scheme",
        "information security",
        "data protection",
        "privacy terms",
        "legal definitions",
        "statutory definitions",
        "regulatory definitions",
        "policy definitions",
        "term definitions",
        "word meanings",
        "concepts",
        "key concepts",
        "fundamental concepts",
      ],
    },
  ],

  // Price List Page
  priceList: [
    {
      label: "Price List – Overview",
      path: "/support-at-home-price-list",
      sectionId: "price-list-overview",
      keywords: [
        "price list",
        "pricing",
        "costs",
        "fees",
        "service prices",
        "hourly rates",
        "support at home prices",
        "ndis prices",
        "hcp prices",
        "aged care prices",
        "disability care prices",
        "care costs",
        "service fees",
        "price guide",
        "cost guide",
        "fee schedule",
        "price schedule",
        "pricing list",
        "rate card",
        "service rates",
        "hourly cost",
        "daily cost",
        "weekly cost",
        "monthly cost",
        "pricing information",
        "cost information",
        "fee information",
        "price details",
        "cost details",
        "fee details",
      ],
    },
    {
      label: "Price List – Main",
      path: "/support-at-home-price-list",
      sectionId: "price-list-main",
      keywords: [
        "support at home price list",
        "price list 2025",
        "2025 prices",
        "current prices",
        "latest prices",
        "updated prices",
        "effective prices",
        "service pricing",
        "support pricing",
        "care pricing",
        "ndis pricing",
        "home care package pricing",
        "aged care pricing",
        "disability care pricing",
        "residential care pricing",
        "in-home care pricing",
        "personal care pricing",
        "nursing care pricing",
        "allied health pricing",
        "therapy pricing",
        "transport pricing",
        "meal pricing",
        "domestic assistance pricing",
        "social support pricing",
        "clinical care pricing",
        "complex care pricing",
        "high intensity care pricing",
        "specialist care pricing",
      ],
    },
    {
      label: "Price List – FAQ Section",
      path: "/support-at-home-price-list",
      sectionId: "faq-section",
      keywords: [
        "price list faq",
        "pricing faq",
        "cost faq",
        "fee faq",
        "price questions",
        "cost questions",
        "fee questions",
        "pricing questions",
        "price list questions",
        "cost concerns",
        "fee concerns",
        "pricing concerns",
        "price clarifications",
        "cost clarifications",
        "fee clarifications",
        "pricing clarifications",
        "price inquiries",
        "cost inquiries",
        "fee inquiries",
        "pricing inquiries",
        "price information",
        "cost information",
        "fee information",
        "pricing information",
        "price help",
        "cost help",
        "fee help",
        "pricing help",
        "price support",
        "cost support",
        "fee support",
        "pricing support",
      ],
    },
    {
      label: "Price List – Get Started",
      path: "/support-at-home-price-list",
      sectionId: "get-started",
      keywords: [
        "get started",
        "ready to get started",
        "book a care plan call",
        "care plan call",
        "start care",
        "begin care",
        "start services",
        "begin services",
        "enroll",
        "enrolment",
        "sign up",
        "register",
        "apply",
        "application",
        "join",
        "become a client",
        "become a resident",
        "start support",
        "begin support",
        "initial consultation",
        "free consultation",
        "care assessment",
        "needs assessment",
        "service assessment",
        "care planning",
        "service planning",
        "support planning",
        "personalised plan",
        "customised plan",
        "tailored plan",
        "individual plan",
        "care consultation",
        "service consultation",
        "support consultation",
        "meet with us",
        "talk to us",
        "contact us",
        "get in touch",
        "reach out",
        "schedule call",
        "book appointment",
        "make appointment",
        "arrange meeting",
        "set up care",
        "set up services",
        "set up support",
      ],
    },
  ],

  // Career Page
  careerPage: [
    {
      label: "Career – Overview",
      path: "/career",
      sectionId: "career-overview",
      keywords: [
        "career",
        "careers",
        "jobs",
        "employment",
        "work",
        "join us",
        "join our team",
        "work with us",
        "career opportunities",
        "job opportunities",
        "employment opportunities",
        "work opportunities",
        "career page",
        "jobs page",
        "employment page",
        "work page",
        "hiring",
        "recruitment",
        "staffing",
        "career information",
        "job information",
        "employment information",
        "work information",
        "career overview",
        "job overview",
        "employment overview",
        "work overview",
        "career introduction",
        "job introduction",
        "employment introduction",
        "work introduction",
        "career details",
        "job details",
        "employment details",
        "work details",
        "career description",
        "job description",
        "employment description",
        "work description",
      ],
    },
    {
      label: "Career – Job Openings",
      path: "/career",
      sectionId: "job-openings",
      keywords: [
        "job openings",
        "open positions",
        "current vacancies",
        "available jobs",
        "job vacancies",
        "position openings",
        "open jobs",
        "vacant positions",
        "job listings",
        "position listings",
        "employment openings",
        "work openings",
        "career openings",
        "opportunities",
        "job opportunities",
        "career opportunities",
        "employment opportunities",
        "work opportunities",
        "job postings",
        "position postings",
        "employment postings",
        "work postings",
        "career postings",
        "job board",
        "career board",
        "employment board",
        "work board",
        "job portal",
        "career portal",
        "employment portal",
        "work portal",
        "job search",
        "career search",
        "employment search",
        "work search",
        "find a job",
        "find employment",
        "find work",
        "find a career",
        "apply for job",
        "apply for position",
        "apply for employment",
        "apply for work",
        "submit application",
        "job application",
        "employment application",
        "work application",
        "career application",
        "hiring now",
        "recruiting now",
        "staffing now",
        "immediate openings",
        "urgent hiring",
        "urgent recruitment",
        "urgent staffing",
        "job categories",
        "career categories",
        "employment categories",
        "work categories",
        "job types",
        "career types",
        "employment types",
        "work types",
        "full-time jobs",
        "part-time jobs",
        "casual jobs",
        "permanent jobs",
        "temporary jobs",
        "contract jobs",
        "shift work",
        "flexible work",
        "remote work",
        "work from home",
        "on-site work",
        "in-person work",
        "caregiver jobs",
        "nurse jobs",
        "nursing jobs",
        "healthcare jobs",
        "aged care jobs",
        "disability care jobs",
        "support worker jobs",
        "care worker jobs",
        "personal care jobs",
        "domestic care jobs",
        "allied health jobs",
        "therapy jobs",
        "rehabilitation jobs",
        "clinical jobs",
        "medical jobs",
        "health jobs",
        "wellbeing jobs",
        "lifestyle jobs",
        "activity jobs",
        "recreation jobs",
        "social jobs",
        "community jobs",
        "administrative jobs",
        "office jobs",
        "management jobs",
        "supervisor jobs",
        "coordinator jobs",
        "team leader jobs",
        "manager jobs",
        "director jobs",
        "executive jobs",
        "support jobs",
        "technical jobs",
        "IT jobs",
        "maintenance jobs",
        "facility jobs",
        "housekeeping jobs",
        "kitchen jobs",
        "catering jobs",
        "food service jobs",
        "laundry jobs",
        "cleaning jobs",
        "gardening jobs",
        "grounds jobs",
        "security jobs",
        "driver jobs",
        "transport jobs",
        "volunteer jobs",
        "volunteering",
        "volunteer opportunities",
        "volunteer work",
        "volunteer positions",
        "internship",
        "internships",
        "traineeship",
        "traineeships",
        "apprenticeship",
        "apprenticeships",
        "graduate program",
        "graduate programs",
        "entry level jobs",
        "experienced jobs",
        "senior jobs",
        "leadership jobs",
        "specialist jobs",
        "expert jobs",
        "professional jobs",
      ],
    },
  ],
};

export const SEARCH_ITEMS = Object.values(PAGE_SEARCH_CONFIG).flat();

export const KEYWORD_TO_SECTION = (() => {
  const map = {};

  Object.values(PAGE_SEARCH_CONFIG).forEach((pageItems) => {
    pageItems.forEach((item) => {
      const sectionId = item.sectionId;
      if (!sectionId) return;

      (item.keywords || []).forEach((kw) => {
        if (!kw) return;
        map[String(kw).toLowerCase()] = sectionId;
      });

      if (item.label) {
        const tokens = String(item.label)
          .toLowerCase()
          .split(/[\s–-]+/);
        tokens.forEach((t) => {
          if (t && !map[t]) {
            map[t] = sectionId;
          }
        });
      }

      map[sectionId.toLowerCase()] = sectionId;
    });
  });

  return map;
})();
